version: '2'
services:

  grafana:
    container_name: local-grafana
    image: grafana/grafana:3.1.1-1470047149
    ports:
      - "3000:3000" # interface port
    links:
      - influxdb

  telegraf:
    container_name: local-telegraf
    image: speedazerty/telegraf:latest
    ports:
      - "8125:8125/udp" # StatsD
      - "8092:8092/udp" # UDP
      - "8094:8094" # TCP
    links:
      - influxdb

  influxdb:
    container_name: local-influxdb
    image: influxdb:1.0.2
    ports:
      - "8086:8086" # HTTP API port
      - "8083:8083" # Administrator interface port
    # environment:
    #   - INFLUXDB_REPORTING_DISABLED=true
    #   - INFLUXDB_META_DIR=/path/to/metadir
    #   - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
